/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MILLIS_COUNTER_CAPT_INT.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "RTC_aliases.h"
#include "RTC.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "i2c_scl_aliases.h"
#include "i2c_scl.h"
#include "i2c_sda_aliases.h"
#include "i2c_sda.h"
#include "DebugLED_aliases.h"
#include "DebugLED.h"
#include "MILLIS_COUNTER.h"
#include "DebugPin_1_aliases.h"
#include "DebugPin_1.h"
#include "CTR_SYNC_EN.h"
#include "mSec_clock_1.h"
#include "SEC_COUNTER.h"
#include "RTC_SEC_COUNTER.h"
#include "MILLIS_CTR_CAPTSEL.h"
#include "BUTTONPRESS_REG.h"
#include "Button_aliases.h"
#include "Button.h"
#include "SEC_CTR_TC_INT.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

