/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "o_DebugLed_aliases.h"
#include "o_DebugLed.h"
#include "SPI_Module.h"
#include "SPI_Module_PVT.h"
#include "MISO_NC_aliases.h"
#include "MISO_NC.h"
#include "Display_DC_aliases.h"
#include "Display_DC.h"
#include "DebugPin_aliases.h"
#include "DebugPin.h"
#include "Display_RST_aliases.h"
#include "Display_RST.h"
#include "Display_CS_aliases.h"
#include "Display_CS.h"
#include "SPI_MOSI_aliases.h"
#include "SPI_MOSI.h"
#include "SPI_SCLK_aliases.h"
#include "SPI_SCLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

